sudo: false
language: python
python:
  - "3.5"
cache:
  apt: true
  pip: false
env: PYCURL_SSL_LIBRARY=gnutls
addons:
  apt:
    packages:
      - libcurl4-gnutls-dev
      - librtmp-dev
install:
  - python setup.py clean --all
  - python setup.py install
script:
  - python -W always setup.py test
matrix:
  allow_failures:
    - python: pypy
